services:
  frontend:
    platform: linux/amd64
    image: umasscds/inatator_frontend:0.2.0
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    platform: linux/amd64
    image: umasscds/inatator_backend:0.2.0
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    ports:
      - "8000:8000"
