services:
  db:
    container_name: inatator_db
    image: postgres:16
    restart: always
    env_file:
      - .docker.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  frontend:
    platform: linux/amd64
    image: umasscds/inatator_frontend:0.2.0
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    platform: linux/amd64
    image: umasscds/inatator_backend:0.2.0
    env_file:
      - .docker.env
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: 
