services:
  frontend:
    platform: linux/amd64
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    platform: linux/amd64
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
