name: inatator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - torch
      - fastapi
      - uvicorn[standard]
      - pytest
      - ruff
      - jupyter
      - matplotlib
      - seaborn
      - sphinx
      