# Creates a new docker image and pushes it to DockerHub when a version tag is created.
name: create-docker-images
on:
  push:
    tags:
      - 'testv*.*'

jobs:
  # Based on instructions from https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
  build-frontend-and-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: 'Create env file'
        run: |
          touch .docker.env
          echo DATABASE_URL=postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@db:5432/${{secrets.POSTGRES_DB}} >> .docker.env
          
      - name: Build and push images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push